<?php
echo"<header>"
."<nav>"
    ."<div class='logo'>"
        ."<img id='nav-logo' src='imgs/identificador-blanco.svg' alt='Logo'>"
        ."<!--<h2 id='logo-text'>Cuisinette</h2>-->"
    ."</div>"
    ."<ul class='menu'>"
        ."<li><a href='#'>Home</a></li>"
        ."<li><a href='#'>About</a></li>"
        ."<li><a href='#'>Sales</a></li>"
        ."<li><a href='#'>Categories</a></li>"
        ."<li><a href='#'>Download</a></li>"
    ."</ul>"
    ."<div class='icons'>"
        ."<img id='shopping-cart' src='imgs/icons/anadir-a-la-cesta.svg' alt='Shopping Cart'>"
        ."<img id='user-menu' src='imgs/icons/usuario.svg' alt='User Menu'>"
    ."</div>"
."</nav>"
."</header>"
?>